# This is the configuration file for the project
# Everything you can tweak it's here

output_dir: "data/processed"

wandb:
 run_name: testing 
 project: franco_slm
 comment: v1

datasets:
  name: "markod0925/TinyStories-Italian"
  num_workers: 8
  output_dir: data/

tokenizer:
  name: "sapienzanlp/Minerva-7B-base-v1.0"
  max_length: 512

model:
  vocab_size: 51200
  d_model: 256
  n_layers: 8
  n_head: 8
  d_ff: 1024
  eps_rms_norm: 1.0e-6
  dropout: 0.1
  seq_len: 512

train:
  seed: 42
  batch_size: 32
  learning_rate: 3.0e-4
  min_lr: 3.0e-5
  max_iters: 200000
  warmup_steps: 1000
  eval_iters: 1000
  generate_every: 1000
  generate_prompt: "C'era una volta"
  generate_max_new_tokens: 100
  generate_temperature: 0.8
  generate_top_k: 50
  grad_clip: 1.0
  weight_decay: 0.1
  betas: [0.9, 0.95]
  adam_eps: 1.0e-8
  lr_decay_start_factor: 0.01
  best_model_params_path: "checkpoints/best_model.pt"

stages:
  data_prep: false
  train: true
  evaluate: false

data_prep:
  total_batches: 1024

hydra:
  run:
    dir: .
  output_subdir: null